# Generated by Django 5.1.7 on 2025-03-21 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roommember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roommember',
            unique_together={('user', 'room')},
        ),
    ]
