# Generated by Django 5.1.7 on 2025-03-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_members_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members_count',
            field=models.IntegerField(default=0),
        ),
    ]
